import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";

export function RiskDisclaimer() {
  return (
    <Alert>
      <AlertTitle>Disclaimer</AlertTitle>
      <AlertDescription>
        This report is generated by an AI system. It indicates potential anomalies and risk
        indicators based on available data. It is not a conclusion of guilt or corruption.
        Human verification is required.
      </AlertDescription>
    </Alert>
  );
}
